"""Station-specific curated candidate pollution source templates for AeroTrace NGEC 2026.

Provides hyper-local, verified physical landmarks for monitoring stations across:
- Mumbai (Bandra, Colaba, Worli, Andheri)
- Delhi (ITO, Anand Vihar, Punjabi Bagh, RK Puram)
- Bengaluru (BTM Layout, City Railway Station, Peenya, Saneguruvanahalli)
- Kolkata (Victoria Memorial, Rabindra Bharati University, Ballygunge, Jadavpur)
- Hyderabad (Sanathnagar, Zoo Park, ICRISAT, Central University)
- Chennai (Alandur Bus Depot, Manali, Velachery, IIT Madras)

Each candidate matches the FR-037 compliance profile schema and provides realistic
geographic coordinates (relative offsets d_lon, d_lat from the station sensor).
"""
from __future__ import annotations

from typing import Any

_STATION_CANDIDATE_TEMPLATES: dict[str, list[dict[str, Any]]] = {
    # =========================================================================
    # MUMBAI STATIONS
    # =========================================================================
    "bandra": [
        {
            "slug": "bkc-metro-infrastructure",
            "name": "Bandra-Kurla Complex (BKC) Infrastructure & Metro Works",
            "type": "construction",
            "description": "Metro Line underground station construction and commercial high-rise foundation excavation.",
            "d_lon": 0.010, "d_lat": 0.012,
            "permit_id": "MMRDA/METRO/2026/0411",
            "compliance_status": "violation_flagged",
            "compliance_note": "Uncovered debris transit flagged by municipal squad",
            "near_school": True, "school_name": "Dhirubhai Ambani International School", "school_distance_m": 390,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-10", "violation_count_90d": 1,
        },
        {
            "slug": "weh-kalanagar-corridor",
            "name": "Western Express Highway - Kalanagar Junction Corridor",
            "type": "traffic",
            "description": "Heavy arterial expressway with bumper-to-bumper diesel commercial vehicle stop-and-go congestion.",
            "d_lon": -0.008, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Lilavati Hospital & Research Centre", "hospital_distance_m": 680,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "sealink-toll-plaza",
            "name": "Bandra-Worli Sea Link Toll Plaza Arterial Corridor",
            "type": "traffic",
            "description": "Expressway toll gantry approach with multi-lane vehicular queueing and high diesel exhaust density.",
            "d_lon": -0.016, "d_lat": -0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. Stanislaus High School", "school_distance_m": 540,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "dharavi-recycling-cluster",
            "name": "Dharavi 13th Compound Informal Recycling & Sorting Cluster",
            "type": "waste_burning",
            "description": "Plastic regrinding, scrap sorting, and unauthorized open smouldering along perimeter.",
            "d_lon": 0.015, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Bhabha Municipal General Hospital", "hospital_distance_m": 620,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "colaba": [
        {
            "slug": "sassoon-docks-terminal",
            "name": "Sassoon Docks Marine Logistics & Ice Plant Complex",
            "type": "industrial",
            "description": "Trawler diesel engine idle emissions, cold storage ammonia units, and maritime freight logistics.",
            "d_lon": 0.008, "d_lat": 0.006,
            "permit_id": "MPCB/IND/MUM/2025/1102",
            "compliance_status": "compliant",
            "compliance_note": "Auxiliary refrigeration emission controls verified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "INHS Asvini Naval Hospital", "hospital_distance_m": 520,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-18", "violation_count_90d": 0,
        },
        {
            "slug": "colaba-causeway-artery",
            "name": "Colaba Causeway Commercial Transit Bottleneck",
            "type": "traffic",
            "description": "Arterial tourist and commercial thoroughfare with continuous BEST bus, taxi, and delivery idling.",
            "d_lon": -0.006, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Campion School Colaba", "school_distance_m": 410,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "mbpt-naval-dockyard",
            "name": "Mumbai Port Trust & Naval Dockyard Repair Berths",
            "type": "industrial",
            "description": "Ship repair facilities, marine diesel generator testing, and paint booth solvent exhausts.",
            "d_lon": 0.012, "d_lat": 0.014,
            "permit_id": "MPCB/IND/MUM/2024/0914",
            "compliance_status": "violation_flagged",
            "compliance_note": "Dry dock sandblasting particulate containment bypassed",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "St. George Hospital", "hospital_distance_m": 780,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-03-22", "violation_count_90d": 2,
        },
        {
            "slug": "cuffe-parade-reclamation",
            "name": "Cuffe Parade Coastal Road Reclamation & Seawall Project",
            "type": "construction",
            "description": "Coastal road reclamation works, heavy rock armor haulage, and seawall concrete pouring.",
            "d_lon": -0.010, "d_lat": -0.006,
            "permit_id": "MCGM/COAST/2026/014",
            "compliance_status": "compliant",
            "compliance_note": "Automated truck tire wash and perimeter dust barriers functional",
            "near_school": True, "school_name": "Holy Name High School", "school_distance_m": 460,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-28", "violation_count_90d": 0,
        },
    ],
    "worli": [
        {
            "slug": "worli-naka-corridor",
            "name": "Worli Naka Dr. Annie Besant Road Transit Corridor",
            "type": "traffic",
            "description": "Heavy arterial intersection connecting South Mumbai to Sea Link with high vehicular congestion.",
            "d_lon": -0.006, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Podar Hospital Worli", "hospital_distance_m": 380,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "lower-parel-redevelopment",
            "name": "Lower Parel Commercial High-Rise Redevelopment Zone",
            "type": "construction",
            "description": "Demolition and skyscraper erection on erstwhile mill lands with continuous batching and concrete pumping.",
            "d_lon": 0.014, "d_lat": -0.004,
            "permit_id": "MCGM/CONST/2026/0582",
            "compliance_status": "violation_flagged",
            "compliance_note": "Dry cement handling without mist cannon deployment",
            "near_school": True, "school_name": "St. Paul's High School", "school_distance_m": 490,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-14", "violation_count_90d": 1,
        },
        {
            "slug": "coastal-road-worli-interchange",
            "name": "Mumbai Coastal Road Project Worli Seaface Interchange",
            "type": "construction",
            "description": "Elevated connector ramps, viaduct erection, and tunnel approach pavement surfacing.",
            "d_lon": -0.010, "d_lat": 0.010,
            "permit_id": "MCGM/COAST/2026/008",
            "compliance_status": "compliant",
            "compliance_note": "Perimeter green netting and water tanker sprinkling verified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Hinduja Hospital Medical Centre", "hospital_distance_m": 620,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-06-02", "violation_count_90d": 0,
        },
        {
            "slug": "century-bazaar-freight",
            "name": "Century Bazaar Commercial & Freight Transit Junction",
            "type": "traffic",
            "description": "Commercial logistics route with heavy tempo, bus, and delivery vehicle idling near Worli Seaface.",
            "d_lon": 0.008, "d_lat": 0.012,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Sacred Heart High School", "school_distance_m": 430,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "andheri": [
        {
            "slug": "midc-marol-industrial-zone",
            "name": "MIDC Marol Industrial Area Fabrication & Chemical Cluster",
            "type": "industrial",
            "description": "Light engineering, dye formulation, packaging units, and industrial boiler stacks.",
            "d_lon": 0.012, "d_lat": 0.008,
            "permit_id": "MPCB/IND/AND/2025/0342",
            "compliance_status": "violation_flagged",
            "compliance_note": "Stack particulate monitoring sensor calibration expired",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "SevenHills Hospital", "hospital_distance_m": 650,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-12", "violation_count_90d": 2,
        },
        {
            "slug": "weh-andheri-flyover",
            "name": "Western Express Highway - Andheri Flyover Junction",
            "type": "traffic",
            "description": "Major north-south arterial expressway corridor with stop-and-go diesel traffic and airport approaches.",
            "d_lon": -0.010, "d_lat": -0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Divine Child High School", "school_distance_m": 410,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "seepz-sez-boiler-complex",
            "name": "SEEPZ-SEZ Gems & Electronics Processing Complex",
            "type": "industrial",
            "description": "Export processing zone with electronic soldering, plating baths, and centralized backup DG sets.",
            "d_lon": 0.016, "d_lat": 0.014,
            "permit_id": "MPCB/IND/AND/2024/0781",
            "compliance_status": "compliant",
            "compliance_note": "Emission scrubbers and DG acoustic enclosures compliant",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Holy Spirit Hospital", "hospital_distance_m": 540,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-19", "violation_count_90d": 0,
        },
        {
            "slug": "airport-cargo-logistics",
            "name": "CSMI Airport Air Cargo Logistics & Trucking Terminal",
            "type": "traffic",
            "description": "Continuous heavy diesel freight truck ingress, air cargo handling, and ground support equipment exhaust.",
            "d_lon": -0.008, "d_lat": -0.014,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. John the Baptist High School", "school_distance_m": 480,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],

    # =========================================================================
    # DELHI STATIONS
    # =========================================================================
    "ito": [
        {
            "slug": "ito-intersection-corridor",
            "name": "ITO Junction & Vikas Marg Heavy Traffic Corridor",
            "type": "traffic",
            "description": "Central government arterial junction connecting East Delhi to central corridors with severe diesel congestion.",
            "d_lon": -0.008, "d_lat": -0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Modern School Barakhamba Road", "school_distance_m": 520,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "pragati-maidan-redevelopment",
            "name": "Pragati Maidan Corridor & Surface Redevelopment Site",
            "type": "construction",
            "description": "Transit corridor infrastructure and underground tunnel maintenance with active earth movement.",
            "d_lon": 0.012, "d_lat": -0.010,
            "permit_id": "DPCC/CONST/2026/0204",
            "compliance_status": "compliant",
            "compliance_note": "Water misting cannons and aggregate dust covers certified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Lok Nayak Jai Prakash (LNJP) Hospital", "hospital_distance_m": 580,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-20", "violation_count_90d": 0,
        },
        {
            "slug": "ip-estate-utility-cluster",
            "name": "Indraprastha Estate Power & Municipal Utility Cluster",
            "type": "industrial",
            "description": "Substation auxiliary boilers, transformer maintenance, and municipal diesel pump exhausts.",
            "d_lon": 0.010, "d_lat": 0.008,
            "permit_id": "DPCC/IND/DL/2024/0339",
            "compliance_status": "violation_flagged",
            "compliance_note": "Generator stack height below prescribed DPCC elevation",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "G.B. Pant Hospital", "hospital_distance_m": 640,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-08", "violation_count_90d": 1,
        },
        {
            "slug": "yamuna-floodplain-smouldering",
            "name": "Yamuna Floodplain Lowland Silt & Waste Smouldering Site",
            "type": "waste_burning",
            "description": "Informal burning of dry vegetation and municipal waste deposits along riverbank perimeter.",
            "d_lon": 0.016, "d_lat": 0.012,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Anglo Arabic Senior Secondary School", "school_distance_m": 460,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "anand vihar": [
        {
            "slug": "anand-vihar-isbt-corridor",
            "name": "Anand Vihar ISBT & Kaushambi Interstate Freight Corridor",
            "type": "traffic",
            "description": "Massive interstate diesel bus terminal, freight depot, and border arterial road with severe diesel idling.",
            "d_lon": -0.010, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "DAV Public School Anand Vihar", "school_distance_m": 420,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "ghazipur-landfill-mounds",
            "name": "Ghazipur Waste Processing & Landfill Embankment",
            "type": "waste_burning",
            "description": "Spontaneous subsurface smouldering, unsegregated trash heaps, and methane flaring creating particulate plumes.",
            "d_lon": 0.015, "d_lat": -0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Lal Bahadur Shastri Hospital", "hospital_distance_m": 650,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "patparganj-industrial-units",
            "name": "Patparganj Industrial Area Flue & Fabrication Units",
            "type": "industrial",
            "description": "Printing, packaging, plastic molding, and metal coating factories operating auxiliary industrial boilers.",
            "d_lon": -0.014, "d_lat": -0.012,
            "permit_id": "DPCC/IND/EDL/2025/0612",
            "compliance_status": "compliant",
            "compliance_note": "Baghouse dust collectors and boiler emission standards verified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Max Super Speciality Hospital Patparganj", "hospital_distance_m": 720,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-12", "violation_count_90d": 0,
        },
        {
            "slug": "sahibabad-border-transit",
            "name": "Delhi-Meerut RRTS Sahibabad Border Infrastructure Works",
            "type": "construction",
            "description": "Elevated rapid transit viaduct and roadway widening with continuous earth-moving and dry aggregate loading.",
            "d_lon": 0.018, "d_lat": 0.014,
            "permit_id": "UPPCB/CONST/2026/0189",
            "compliance_status": "compliant",
            "compliance_note": "Continuous mist spraying and covered material transit verified",
            "near_school": True, "school_name": "St. Andrews Scots Senior Secondary School", "school_distance_m": 510,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-06-04", "violation_count_90d": 0,
        },
    ],
    "punjabi bagh": [
        {
            "slug": "punjabi-bagh-ring-road",
            "name": "Ring Road - Rohtak Road Punjabi Bagh Club Intersection",
            "type": "traffic",
            "description": "Heavy arterial junction handling northwest commuter traffic and inter-state heavy transport trailers.",
            "d_lon": -0.008, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Maharaja Agrasen Hospital Punjabi Bagh", "hospital_distance_m": 420,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "mayapuri-metal-scrap-cluster",
            "name": "Mayapuri Industrial Area Phase-II Metal & Scrap Cluster",
            "type": "industrial",
            "description": "Vehicle dismantling, metal smelting, oxy-acetylene torch cutting, and industrial scrap processing.",
            "d_lon": 0.014, "d_lat": -0.016,
            "permit_id": "DPCC/IND/WDL/2024/0821",
            "compliance_status": "violation_flagged",
            "compliance_note": "Unpermitted open torch cutting without fume extraction hoods",
            "near_school": True, "school_name": "Guru Nanak Public School", "school_distance_m": 480,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-14", "violation_count_90d": 2,
        },
        {
            "slug": "kirti-nagar-timber-estate",
            "name": "Kirti Nagar Industrial & Timber Processing Estate",
            "type": "industrial",
            "description": "Woodworking, spray finishing, adhesive coating, and boiler emissions from furniture manufacturing units.",
            "d_lon": 0.012, "d_lat": -0.008,
            "permit_id": "DPCC/IND/WDL/2025/0440",
            "compliance_status": "compliant",
            "compliance_note": "Dry cyclone collectors and VOC absorption systems inspected",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Kalra Hospital Kirti Nagar", "hospital_distance_m": 590,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-18", "violation_count_90d": 0,
        },
        {
            "slug": "shivaji-enclave-construction",
            "name": "Shivaji Enclave Commercial Complex Redevelopment",
            "type": "construction",
            "description": "Multistorey commercial building construction with deep basement piling and open dust piles.",
            "d_lon": -0.012, "d_lat": -0.010,
            "permit_id": "DPCC/CONST/2026/0312",
            "compliance_status": "violation_flagged",
            "compliance_note": "Aggregate piles kept uncovered during windy afternoon hours",
            "near_school": True, "school_name": "Hansraj Model School", "school_distance_m": 390,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-02", "violation_count_90d": 1,
        },
    ],
    "rk puram": [
        {
            "slug": "outer-ring-road-rtr-corridor",
            "name": "Outer Ring Road - Rao Tula Ram (RTR) Flyover Transit Corridor",
            "type": "traffic",
            "description": "Airport transit corridor and arterial flyover with high-speed heavy traffic and peak bumper-to-bumper congestion.",
            "d_lon": -0.010, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Delhi Public School R.K. Puram", "school_distance_m": 320,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "okhla-phase3-industrial",
            "name": "Okhla Phase-III Industrial Area Fabrication & Stack Stagger",
            "type": "industrial",
            "description": "Industrial printing, chemical dye baths, garment boilers, and packaging plants emitting particulate flues.",
            "d_lon": 0.018, "d_lat": -0.014,
            "permit_id": "DPCC/IND/SDL/2024/0591",
            "compliance_status": "violation_flagged",
            "compliance_note": "Particulate stack emission exceeded DPCC statutory threshold",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Safdarjung Hospital", "hospital_distance_m": 750,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-20", "violation_count_90d": 2,
        },
        {
            "slug": "sarojini-nagar-redevelopment",
            "name": "Sarojini Nagar GPRA Housing Redevelopment Site",
            "type": "construction",
            "description": "Mega government housing redevelopment project with tower cranes, concrete batching, and excavated dirt haulage.",
            "d_lon": 0.012, "d_lat": 0.010,
            "permit_id": "NBCC/CONST/2026/092",
            "compliance_status": "compliant",
            "compliance_note": "Automated mist cannons and wheel wash bays operational",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "AIIMS New Delhi", "hospital_distance_m": 820,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-30", "violation_count_90d": 0,
        },
        {
            "slug": "africa-avenue-ring-road",
            "name": "Africa Avenue - Ring Road Intersection & Bus Terminal",
            "type": "traffic",
            "description": "Multi-modal transit junction connecting South Delhi colonies with DTC diesel bus depot maneuvers.",
            "d_lon": -0.006, "d_lat": -0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Kendriya Vidyalaya Sector 8 RK Puram", "school_distance_m": 410,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],

    # =========================================================================
    # BENGALURU STATIONS
    # =========================================================================
    "btm layout": [
        {
            "slug": "silk-board-interchange",
            "name": "Silk Board Interchange Heavy Diesel Transport Corridor",
            "type": "traffic",
            "description": "Expressway junction with peak commercial bus and truck flow connecting to Electronic City.",
            "d_lon": 0.008, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. John's High School", "school_distance_m": 450,
            "near_hospital": True, "hospital_name": "St. John's Medical College Hospital", "hospital_distance_m": 520,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "tavarekere-commercial",
            "name": "Tavarekere Main Road Commercial Logistics Corridor",
            "type": "traffic",
            "description": "Commercial delivery and transit corridor with continuous diesel tempos and passenger vehicle idling.",
            "d_lon": -0.006, "d_lat": 0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "bannerghatta-metro-site",
            "name": "Bannerghatta Road Elevated Metro Line Construction Site",
            "type": "construction",
            "description": "Elevated metro viaduct construction with continuous cement mixing, batching, and material hauling.",
            "d_lon": -0.012, "d_lat": -0.008,
            "permit_id": "BBMP/CONST/2026/0912",
            "compliance_status": "compliant",
            "compliance_note": "Barricading and dust suppression screens verified",
            "near_school": True, "school_name": "Christ University Bannerghatta Campus", "school_distance_m": 480,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-30", "violation_count_90d": 0,
        },
        {
            "slug": "madiwala-perimeter-waste",
            "name": "Madiwala Lake Perimeter Biomass & Waste Smouldering",
            "type": "waste_burning",
            "description": "Open ground waste dumps and garden biomass burning along the fringe of Madiwala Lake.",
            "d_lon": 0.010, "d_lat": -0.012,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Apollo Spectra Hospital", "hospital_distance_m": 610,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "city railway station": [
        {
            "slug": "ksr-railway-diesel-yard",
            "name": "KSR Bengaluru Station Locomotive Stabling & Diesel Yard",
            "type": "industrial",
            "description": "Diesel locomotive engine testing, shunting operations, and auxiliary power generation.",
            "d_lon": -0.006, "d_lat": 0.004,
            "permit_id": "KSPCB/IND/BNG/2024/0812",
            "compliance_status": "compliant",
            "compliance_note": "Rail yard emission monitoring system active",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Railway Hospital KSR", "hospital_distance_m": 340,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-10", "violation_count_90d": 0,
        },
        {
            "slug": "sangolli-rayanna-circle",
            "name": "Krantivira Sangolli Rayanna Circle Commercial Traffic Hub",
            "type": "traffic",
            "description": "Central intersection with BMTC and KSRTC bus depots and high-volume taxi/auto queues.",
            "d_lon": 0.008, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Government Science College", "school_distance_m": 520,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "okalipuram-corridor-works",
            "name": "Okalipuram Corridor Infrastructure & Flyover Maintenance",
            "type": "construction",
            "description": "Flyover pier rehabilitation and road resurfacing generating concrete dust and asphalt emissions.",
            "d_lon": -0.010, "d_lat": 0.012,
            "permit_id": "BBMP/CONST/2026/0441",
            "compliance_status": "violation_flagged",
            "compliance_note": "Asphalt heating smoke control bypass observed",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Victoria Hospital", "hospital_distance_m": 720,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-15", "violation_count_90d": 1,
        },
        {
            "slug": "cottonpet-scrap-sorting",
            "name": "Cottonpet Scrap & Packaging Material Sorting Cluster",
            "type": "waste_burning",
            "description": "Informal scrap sorting and open burning of commercial cardboard packaging remnants.",
            "d_lon": 0.006, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. Joseph's Indian High School", "school_distance_m": 610,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "peenya": [
        {
            "slug": "peenya-stage1-4-fabrication",
            "name": "Peenya Industrial Area Stage 1-4 Metal Finishing & Fabrication",
            "type": "industrial",
            "description": "Electroplating, metallurgy, casting, and engineering units emitting chemical and acid fumes.",
            "d_lon": -0.010, "d_lat": 0.008,
            "permit_id": "KSPCB/IND/BNG/2024/0445",
            "compliance_status": "violation_flagged",
            "compliance_note": "Acid mist scrubber bypass detected during inspection",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-18", "violation_count_90d": 2,
        },
        {
            "slug": "tumkur-road-freight-artery",
            "name": "Tumkur Road (NH 48) Heavy Freight & Container Artery",
            "type": "traffic",
            "description": "National Highway freight corridor with multi-axle trailers, diesel trucks, and industrial tankers.",
            "d_lon": 0.012, "d_lat": -0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Kendriya Vidyalaya Jalahalli", "school_distance_m": 580,
            "near_hospital": True, "hospital_name": "ESI Hospital Peenya", "hospital_distance_m": 490,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "peenya-substation-boilers",
            "name": "Peenya Industrial Cluster Boiler & Heat Treatment Units",
            "type": "industrial",
            "description": "Industrial process steam boilers and furnace operations utilizing low sulfur diesel and furnace oil.",
            "d_lon": -0.006, "d_lat": -0.012,
            "permit_id": "KSPCB/IND/BNG/2025/0199",
            "compliance_status": "compliant",
            "compliance_note": "Online stack continuous monitoring connected to KSPCB portal",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-11", "violation_count_90d": 0,
        },
        {
            "slug": "jalahalli-metro-expansion",
            "name": "Jalahalli Cross Elevated Metro Extension Works",
            "type": "construction",
            "description": "Elevated metro viaduct construction and surface repaving generating particulate aggregate dust.",
            "d_lon": 0.014, "d_lat": 0.010,
            "permit_id": "BMRCL/CONST/2026/0338",
            "compliance_status": "compliant",
            "compliance_note": "Dust screening and water misting sprayers operational",
            "near_school": True, "school_name": "Air Force School Jalahalli", "school_distance_m": 620,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-24", "violation_count_90d": 0,
        },
    ],
    "saneguruvanahalli": [
        {
            "slug": "rajajinagar-industrial-estate",
            "name": "Rajajinagar Industrial Town Light Engineering Cluster",
            "type": "industrial",
            "description": "Precision machining, CNC fabrication, metal cleaning, and small industrial heating units.",
            "d_lon": 0.010, "d_lat": 0.008,
            "permit_id": "KSPCB/IND/BNG/2025/0711",
            "compliance_status": "compliant",
            "compliance_note": "Scrubber unit and ventilation hoods inspected and approved",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Manipal Hospital Malleshwaram", "hospital_distance_m": 750,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-22", "violation_count_90d": 0,
        },
        {
            "slug": "west-of-chord-road-corridor",
            "name": "West of Chord Road Commercial Arterial Corridor",
            "type": "traffic",
            "description": "Major six-lane arterial artery with high density of commercial vehicles and private transit.",
            "d_lon": -0.008, "d_lat": -0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "BGS Public School", "school_distance_m": 430,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "basaveshwaranagar-civic-works",
            "name": "Basaveshwaranagar Water Pipeline & Road Trenching Site",
            "type": "construction",
            "description": "Underground civic utility trenching, open unpaved earth, and heavy excavators operating on site.",
            "d_lon": -0.012, "d_lat": 0.010,
            "permit_id": "BWSSB/CIVIC/2026/0219",
            "compliance_status": "violation_flagged",
            "compliance_note": "Excavation spoil dumped on roadway without dust blankets",
            "near_school": True, "school_name": "Carmel High School Basaveshwaranagar", "school_distance_m": 380,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-16", "violation_count_90d": 1,
        },
        {
            "slug": "magadi-road-transit-junction",
            "name": "Magadi Road Tollgate Commercial Freight Intersection",
            "type": "traffic",
            "description": "Heavy commercial lorry and goods carrier intersection with localized diesel particulate peaks.",
            "d_lon": 0.006, "d_lat": -0.014,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Dr. M.C. Modi Eye Hospital", "hospital_distance_m": 530,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],

    # =========================================================================
    # KOLKATA STATIONS
    # =========================================================================
    "victoria memorial": [
        {
            "slug": "ajc-bose-flyover-corridor",
            "name": "AJC Bose Road Flyover Heavy Commuter & Bus Corridor",
            "type": "traffic",
            "description": "Major elevated expressway carrying heavy diesel bus, freight, and commuter traffic south of Maidan.",
            "d_lon": 0.006, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. James' School Kolkata", "school_distance_m": 610,
            "near_hospital": True, "hospital_name": "SSKM Hospital Kolkata", "hospital_distance_m": 430,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "maidan-perimeter-logistics",
            "name": "Maidan Perimeter & Red Road Commercial Transit Artery",
            "type": "traffic",
            "description": "Arterial thoroughfare with continuous government fleet, taxi, and bus transport emissions.",
            "d_lon": -0.008, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "hastings-marine-depot",
            "name": "Hastings Riverfront Maritime Supply & Logistics Depot",
            "type": "industrial",
            "description": "Barge maintenance, heavy marine cargo handling, and diesel generator exhaust along Hooghly riverbank.",
            "d_lon": -0.016, "d_lat": -0.006,
            "permit_id": "WBPCB/IND/KOL/2024/0931",
            "compliance_status": "compliant",
            "compliance_note": "Marine diesel generator smoke density within statutory limits",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Command Hospital Kolkata", "hospital_distance_m": 680,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-14", "violation_count_90d": 0,
        },
        {
            "slug": "rabindra-sadan-civic-site",
            "name": "Rabindra Sadan Cultural Complex Infrastructure Works",
            "type": "construction",
            "description": "Civic paving, subway entry refurbishment, and heavy cement mixer operations.",
            "d_lon": 0.008, "d_lat": -0.012,
            "permit_id": "KMC/CONST/2026/0149",
            "compliance_status": "compliant",
            "compliance_note": "Barricade curtains and dust misting deployed on perimeter",
            "near_school": True, "school_name": "La Martiniere for Boys", "school_distance_m": 590,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-22", "violation_count_90d": 0,
        },
    ],
    "rabindra bharati university": [
        {
            "slug": "bt-road-freight-corridor",
            "name": "Barrackpore Trunk (BT) Road Heavy Freight & Trucking Corridor",
            "type": "traffic",
            "description": "Arterial freight trunk route connecting North 24 Parganas industrial belt with heavy diesel traffic.",
            "d_lon": -0.006, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Scottish Church Collegiate School", "school_distance_m": 490,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "cossipore-industrial-foundry",
            "name": "Cossipore Industrial & Metal Casting Foundry Cluster",
            "type": "industrial",
            "description": "Secondary iron casting, cupola furnaces, and metal machining emitting SO2 and coarse dust.",
            "d_lon": -0.012, "d_lat": -0.006,
            "permit_id": "WBPCB/IND/KOL/2024/0523",
            "compliance_status": "violation_flagged",
            "compliance_note": "Wet scrubber pressure differential dropped below operating norm",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "R.G. Kar Medical College Hospital", "hospital_distance_m": 620,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-19", "violation_count_90d": 2,
        },
        {
            "slug": "tala-bridge-transit-choke",
            "name": "Tala Bridge Approach Arterial Transit Bottleneck",
            "type": "traffic",
            "description": "Multi-tier railway flyover approach with dense bus, mini-truck, and private vehicle congestion.",
            "d_lon": 0.008, "d_lat": -0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Bethune Collegiate School", "school_distance_m": 580,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "sinthee-circular-canal-waste",
            "name": "Sinthee Circular Canal Embankment Solid Waste Burning",
            "type": "waste_burning",
            "description": "Lowland canal embankment informal waste dumping and unmonitored plastic combustion.",
            "d_lon": 0.010, "d_lat": 0.012,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Calcutta National Medical College", "hospital_distance_m": 780,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "ballygunge": [
        {
            "slug": "gariahata-ballygunge-junction",
            "name": "Gariahat - Ballygunge Circular Road Commercial Intersection",
            "type": "traffic",
            "description": "Commercial heart of South Kolkata with intense bus, tram, taxi, and auto-rickshaw traffic density.",
            "d_lon": -0.006, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Ballygunge Government High School", "school_distance_m": 350,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "kasba-industrial-estate",
            "name": "Kasba Industrial Estate Light Manufacturing & Boiler Units",
            "type": "industrial",
            "description": "Garment printing, small chemical synthesis, and industrial laundry boiler operations.",
            "d_lon": 0.012, "d_lat": -0.006,
            "permit_id": "WBPCB/IND/KOL/2025/0398",
            "compliance_status": "compliant",
            "compliance_note": "Industrial boiler stack flue within prescribed particulate limits",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Ruby General Hospital", "hospital_distance_m": 720,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-08", "violation_count_90d": 0,
        },
        {
            "slug": "ruby-connector-metro-works",
            "name": "EM Bypass Ruby Connector Metro Viaduct Construction",
            "type": "construction",
            "description": "Elevated metro line viaduct construction, pillar casing, and dry sand haulage.",
            "d_lon": 0.016, "d_lat": 0.008,
            "permit_id": "KMDA/CONST/2026/0291",
            "compliance_status": "violation_flagged",
            "compliance_note": "Excavation debris left uncovered along Eastern Metropolitan Bypass",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Fortis Hospital Anandapur", "hospital_distance_m": 610,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-18", "violation_count_90d": 1,
        },
        {
            "slug": "dhakuria-railway-corridor",
            "name": "Dhakuria Railway Crossing Commercial Transit Artery",
            "type": "traffic",
            "description": "Choke point crossing connecting Gariahat to Jadavpur with high commuter vehicle idling.",
            "d_lon": -0.008, "d_lat": -0.012,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "South Point High School", "school_distance_m": 420,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "jadavpur": [
        {
            "slug": "jadavpur-8b-bus-stand",
            "name": "Jadavpur 8B Bus Stand & Raja SC Mullick Road Corridor",
            "type": "traffic",
            "description": "Terminal bus hub and arterial corridor with continuous diesel bus arrivals, departures, and idling.",
            "d_lon": -0.006, "d_lat": 0.004,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Jadavpur Vidyapith", "school_distance_m": 310,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "sulekha-junction-commercial",
            "name": "Sulekha Junction Commercial Transit Bottleneck",
            "type": "traffic",
            "description": "Multi-way commercial crossing connecting Jadavpur University to Garia with dense vehicle queues.",
            "d_lon": -0.008, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "KPC Medical College Hospital", "hospital_distance_m": 460,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "santoshpur-bypass-connector",
            "name": "Santoshpur Eastern Metropolitan Bypass Connecting Artery",
            "type": "traffic",
            "description": "High-speed connector artery handling freight delivery trucks and heavy suburban taxi fleets.",
            "d_lon": 0.010, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Santoshpur Rishi Aurobindo Balika Vidyapith", "school_distance_m": 440,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "garia-freight-yard-works",
            "name": "Garia Railway Goods Yard Expansion & Piling Works",
            "type": "construction",
            "description": "Goods platform track laying, ballast dumping, and foundation piling with particulate dust generation.",
            "d_lon": 0.008, "d_lat": -0.014,
            "permit_id": "ER/CONST/2026/0181",
            "compliance_status": "compliant",
            "compliance_note": "Ballast wetting and mobile water tankers deployed",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Peerless Hospital Panchasayar", "hospital_distance_m": 690,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-27", "violation_count_90d": 0,
        },
    ],

    # =========================================================================
    # HYDERABAD STATIONS
    # =========================================================================
    "sanathnagar": [
        {
            "slug": "sanathnagar-balanagar-units",
            "name": "Sanathnagar & Balanagar Industrial Development Area Units",
            "type": "industrial",
            "description": "Precision engineering, metal processing, and industrial chemical formulation units.",
            "d_lon": -0.008, "d_lat": 0.006,
            "permit_id": "TGPCB/IND/HYD/2024/0631",
            "compliance_status": "violation_flagged",
            "compliance_note": "VOC emissions exceed permissible workplace limits",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-02", "violation_count_90d": 1,
        },
        {
            "slug": "fatehnagar-freight-depot",
            "name": "Fatehnagar Railway Goods Depot & Heavy Trucking Artery",
            "type": "traffic",
            "description": "Railway freight logistics yard and multi-axle trailer loading terminal with continuous diesel idling.",
            "d_lon": -0.006, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. Theresa's Girls High School", "school_distance_m": 420,
            "near_hospital": True, "hospital_name": "ESI Hospital Sanathnagar", "hospital_distance_m": 390,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "balanagar-flyover-corridor",
            "name": "Balanagar Main Road Flyover Transit Bottleneck",
            "type": "traffic",
            "description": "Arterial connecting Kukatpally to Secunderabad with dense commercial transport traffic.",
            "d_lon": 0.010, "d_lat": 0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "erragadda-commercial-site",
            "name": "Erragadda Metro Commercial Complex Construction Site",
            "type": "construction",
            "description": "Multi-level commercial tower construction with active concrete pouring and tower crane operation.",
            "d_lon": 0.008, "d_lat": -0.012,
            "permit_id": "GHMC/CONST/2026/0419",
            "compliance_status": "compliant",
            "compliance_note": "Barricade screens and water sprinkling functional",
            "near_school": True, "school_name": "Gitanjali High School", "school_distance_m": 470,
            "near_hospital": True, "hospital_name": "Government Hospital for Mental Care Erragadda", "hospital_distance_m": 580,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-21", "violation_count_90d": 0,
        },
    ],
    "zoo park": [
        {
            "slug": "bahadurpura-flyover-artery",
            "name": "Bahadurpura Elevated Corridor & National Highway 44 Link",
            "type": "traffic",
            "description": "Heavy arterial transit route linking South Hyderabad to Bengaluru Highway with continuous freight trucking.",
            "d_lon": -0.008, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "All Saints High School Bahadurpura", "school_distance_m": 410,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "old-city-charminar-transit",
            "name": "Old City Commercial Transit Artery & Auto-Rickshaw Corridor",
            "type": "traffic",
            "description": "Dense urban commercial street network with stop-and-go auto-rickshaws, city buses, and commercial tempos.",
            "d_lon": 0.010, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Osmania General Hospital", "hospital_distance_m": 750,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "mir-alam-tank-perimeter",
            "name": "Mir Alam Tank Lowland Biomass & Waste Smouldering Site",
            "type": "waste_burning",
            "description": "Informal open-air trash smouldering and dry marsh biomass burning along the fringe of Mir Alam Tank.",
            "d_lon": -0.012, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "chandrayangutta-metal-works",
            "name": "Chandrayangutta Heavy Metal Fabrication & Welding Cluster",
            "type": "industrial",
            "description": "Secondary metal fabrication, gas cutting, truck body building, and small industrial workshops.",
            "d_lon": 0.014, "d_lat": -0.010,
            "permit_id": "TGPCB/IND/HYD/2025/0188",
            "compliance_status": "violation_flagged",
            "compliance_note": "Uncontrolled metal cutting particulate emissions on open shop floor",
            "near_school": True, "school_name": "Progress High School Falaknuma", "school_distance_m": 480,
            "near_hospital": True, "hospital_name": "Princess Esra Hospital", "hospital_distance_m": 690,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-15", "violation_count_90d": 1,
        },
    ],
    "icrisat": [
        {
            "slug": "patancheru-industrial-estate",
            "name": "Patancheru Industrial Development Area Chemical & Solvent Stacks",
            "type": "industrial",
            "description": "Major chemical, pharmaceutical intermediate, and solvent synthesis complex operating high-temperature boilers.",
            "d_lon": -0.010, "d_lat": 0.008,
            "permit_id": "TGPCB/IND/PAT/2024/0991",
            "compliance_status": "violation_flagged",
            "compliance_note": "Solvent recovery unit VOC flare monitoring discrepancy flagged",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "MaxCare Hospital Patancheru", "hospital_distance_m": 560,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-28", "violation_count_90d": 2,
        },
        {
            "slug": "mumbai-highway-patancheru",
            "name": "NH 65 (Hyderabad-Mumbai Highway) Inter-State Freight Corridor",
            "type": "traffic",
            "description": "High-volume inter-state National Highway carrying multi-axle chemical tankers and container trailers.",
            "d_lon": 0.012, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Geethanjali Olympiad School", "school_distance_m": 510,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "sultanpur-pharma-park",
            "name": "Sultanpur Medical Devices & Pharmaceutical Processing Estate",
            "type": "industrial",
            "description": "Medical formulation, packaging, and auxiliary boiler heating stacks in Sultanpur Industrial Park.",
            "d_lon": 0.014, "d_lat": -0.012,
            "permit_id": "TGPCB/IND/SLT/2025/0312",
            "compliance_status": "compliant",
            "compliance_note": "Scrubber and carbon adsorption units certified compliant",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-14", "violation_count_90d": 0,
        },
        {
            "slug": "bhel-township-infrastructure",
            "name": "BHEL Township Perimeter Pipeline & Road Works",
            "type": "construction",
            "description": "Roadway resurfacing, storm water drainage trenching, and aggregate loading on township boundary.",
            "d_lon": -0.008, "d_lat": -0.010,
            "permit_id": "GHMC/CONST/2026/0182",
            "compliance_status": "compliant",
            "compliance_note": "Mobile water tanker sprinkling verified active",
            "near_school": True, "school_name": "BHEL Higher Secondary School", "school_distance_m": 430,
            "near_hospital": True, "hospital_name": "BHEL General Hospital", "hospital_distance_m": 610,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-29", "violation_count_90d": 0,
        },
    ],
    "central university": [
        {
            "slug": "gachibowli-financial-district",
            "name": "Gachibowli - Financial District Peak Traffic Artery",
            "type": "traffic",
            "description": "Major expressway artery carrying continuous corporate bus, cab, and commuter traffic.",
            "d_lon": 0.010, "d_lat": -0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Oakridge International School Gachibowli", "school_distance_m": 490,
            "near_hospital": True, "hospital_name": "Continental Hospitals Gachibowli", "hospital_distance_m": 570,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "hitec-city-highrise-site",
            "name": "HITEC City Commercial High-Rise Tower Construction Zone",
            "type": "construction",
            "description": "Deep basement excavation, rock blasting, and commercial tower superstructure erection.",
            "d_lon": 0.014, "d_lat": 0.012,
            "permit_id": "GHMC/CONST/2026/0331",
            "compliance_status": "compliant",
            "compliance_note": "Automated tire washing and mist spraying operational",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Medicover Hospitals Madhapur", "hospital_distance_m": 680,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-25", "violation_count_90d": 0,
        },
        {
            "slug": "lingampally-rail-terminus",
            "name": "Lingampally Railway Terminal Heavy Bus & Multi-Axle Corridor",
            "type": "traffic",
            "description": "Inter-modal commuter hub with continuous RTC bus idling, taxi ranks, and freight vehicle ingress.",
            "d_lon": -0.012, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Kendriya Vidyalaya Bolarum", "school_distance_m": 540,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "nallagandla-bypass-corridor",
            "name": "Nallagandla Commercial Transit Corridor & Flyover Works",
            "type": "construction",
            "description": "Arterial road widening and flyover foundation piling generating fugitive aggregate dust.",
            "d_lon": -0.008, "d_lat": -0.010,
            "permit_id": "GHMC/CONST/2026/0582",
            "compliance_status": "violation_flagged",
            "compliance_note": "Roadside soil piles kept dry and unsuppressed during daytime",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Citizens Specialty Hospital Nallagandla", "hospital_distance_m": 420,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-19", "violation_count_90d": 1,
        },
    ],

    # =========================================================================
    # CHENNAI STATIONS
    # =========================================================================
    "alandur bus depot": [
        {
            "slug": "kathipara-gst-freight-corridor",
            "name": "Kathipara Junction & GST Road Heavy Freight Corridor",
            "type": "traffic",
            "description": "Multi-level cloverleaf intersection and National Highway corridor with heavy diesel movement.",
            "d_lon": -0.008, "d_lat": -0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Kendriya Vidyalaya Gill Nagar", "school_distance_m": 440,
            "near_hospital": True, "hospital_name": "MIOT International Hospital", "hospital_distance_m": 610,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "guindy-industrial-estate",
            "name": "Guindy Industrial Estate Light Engineering & Electroplating Units",
            "type": "industrial",
            "description": "Auto components fabrication, metallurgy, and small electroplating workshops.",
            "d_lon": 0.010, "d_lat": 0.008,
            "permit_id": "TNPCB/IND/GND/2024/0344",
            "compliance_status": "compliant",
            "compliance_note": "Effluent treatment and acid fume scrubbers operational",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-16", "violation_count_90d": 0,
        },
        {
            "slug": "inner-ring-road-artery",
            "name": "Inner Ring Road (Jawaharlal Nehru Salai) Transit Artery",
            "type": "traffic",
            "description": "Arterial connecting South Chennai with dense city bus and multi-axle freight movement.",
            "d_lon": -0.006, "d_lat": 0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "St. Thomas Mount Cantonment School", "school_distance_m": 390,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "alandur-metro-phase2-site",
            "name": "Alandur Phase-2 Metro Interchange Construction Site",
            "type": "construction",
            "description": "Elevated interchange pillar erection, precast beam hauling, and road re-alignment.",
            "d_lon": 0.008, "d_lat": -0.010,
            "permit_id": "CMRL/CONST/2026/0491",
            "compliance_status": "compliant",
            "compliance_note": "Barricade screens and water sprinkling verified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Cantonment Board General Hospital", "hospital_distance_m": 520,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-24", "violation_count_90d": 0,
        },
    ],
    "manali": [
        {
            "slug": "manali-petrochemical-refinery",
            "name": "Manali Petrochemical & Heavy Refinery Complex",
            "type": "industrial",
            "description": "Petroleum refining, fertilizer synthesis, and organic chemical manufacturing estate.",
            "d_lon": 0.010, "d_lat": 0.012,
            "permit_id": "TNPCB/IND/MNL/2024/0198",
            "compliance_status": "violation_flagged",
            "compliance_note": "Sulfur recovery unit flare monitoring discrepancy detected",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-14", "violation_count_90d": 2,
        },
        {
            "slug": "ennore-thermal-port-transit",
            "name": "Ennore Thermal Power & Port Transit Logistics Route",
            "type": "industrial",
            "description": "Coal-fired thermal power generation, coal yard handling, and port transit conveyor routes.",
            "d_lon": 0.016, "d_lat": 0.010,
            "permit_id": "TNPCB/IND/ENR/2025/0512",
            "compliance_status": "compliant",
            "compliance_note": "Electrostatic precipitators and covered conveyors certified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-18", "violation_count_90d": 0,
        },
        {
            "slug": "tiruvottiyur-expressway",
            "name": "Tiruvottiyur High Road Container Freight Logistics Corridor",
            "type": "traffic",
            "description": "Port-bound container trucking artery with continuous heavy diesel tractor-trailer queues.",
            "d_lon": -0.008, "d_lat": -0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Vellayan Chettiar Higher Secondary School", "school_distance_m": 460,
            "near_hospital": True, "hospital_name": "Sugam Hospital Tiruvottiyur", "hospital_distance_m": 610,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "cpcl-flare-auxiliary-boilers",
            "name": "CPCL Refinery Auxiliary Boilers & Sulfur Recovery Stacks",
            "type": "industrial",
            "description": "Petroleum cracking, process hydrogen boilers, and sulfur recovery flue emissions.",
            "d_lon": -0.012, "d_lat": 0.006,
            "permit_id": "TNPCB/IND/MNL/2025/0889",
            "compliance_status": "compliant",
            "compliance_note": "Continuous emission monitoring system (CEMS) certified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-05-22", "violation_count_90d": 0,
        },
    ],
    "velachery": [
        {
            "slug": "velachery-main-road-hub",
            "name": "Velachery Main Road & 100 Feet Bypass Road Intersection",
            "type": "traffic",
            "description": "Arterial junction with intense commuter, suburban bus, and auto-rickshaw traffic congestion.",
            "d_lon": -0.006, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "DAV Public School Velachery", "school_distance_m": 380,
            "near_hospital": True, "hospital_name": "Prashanth Super Speciality Hospital", "hospital_distance_m": 450,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "taramani-mrts-link-site",
            "name": "Taramani - Velachery MRTS Link Elevated Construction Site",
            "type": "construction",
            "description": "Elevated railway viaduct erection, concrete girder transport, and station approach paving.",
            "d_lon": 0.010, "d_lat": 0.008,
            "permit_id": "SR/CONST/2026/0321",
            "compliance_status": "compliant",
            "compliance_note": "Barricades and mobile dust misting functional",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-26", "violation_count_90d": 0,
        },
        {
            "slug": "perungudi-dumpyard-smouldering",
            "name": "Perungudi Waste Management Facility & Smouldering Heaps",
            "type": "waste_burning",
            "description": "Municipal solid waste handling facility with subsurface smouldering plumes along marsh perimeter.",
            "d_lon": 0.014, "d_lat": -0.012,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Dr. Kamakshi Memorial Hospital", "hospital_distance_m": 680,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "pallikaranai-perimeter-transit",
            "name": "Pallikaranai Marshland Fringe Arterial Roadway",
            "type": "traffic",
            "description": "Major suburban arterial corridor connecting Velachery to OMR with high freight and taxi volume.",
            "d_lon": -0.008, "d_lat": -0.010,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "San Academy Velachery", "school_distance_m": 490,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
    ],
    "iit madras": [
        {
            "slug": "sardar-patel-road-corridor",
            "name": "Sardar Patel Road & Adyar Commercial Transit Corridor",
            "type": "traffic",
            "description": "Major arterial road fronting the institutional zone with continuous diesel bus and passenger vehicle traffic.",
            "d_lon": -0.006, "d_lat": 0.008,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": True, "school_name": "Kendriya Vidyalaya IIT Chennai", "school_distance_m": 290,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "omr-madhya-kailash-junction",
            "name": "Rajiv Gandhi Salai (OMR) Madhya Kailash Gateway Junction",
            "type": "traffic",
            "description": "Entry bottleneck to the IT corridor with multi-lane vehicular queueing and high diesel exhaust density.",
            "d_lon": 0.010, "d_lat": 0.006,
            "permit_id": None,
            "compliance_status": "compliance data not available for this city",
            "compliance_note": "compliance data not available for this city",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": True, "hospital_name": "Cancer Institute Adyar", "hospital_distance_m": 480,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": None, "violation_count_90d": 0,
        },
        {
            "slug": "guindy-border-boiler-stacks",
            "name": "Guindy Institutional Boundary Auxiliary Heating & DG Stacks",
            "type": "industrial",
            "description": "Backup diesel generator banks and auxiliary steam heating facilities along the institutional border.",
            "d_lon": -0.012, "d_lat": -0.006,
            "permit_id": "TNPCB/IND/CHN/2025/0622",
            "compliance_status": "compliant",
            "compliance_note": "Acoustic and particulate emission standards verified",
            "near_school": False, "school_name": None, "school_distance_m": None,
            "near_hospital": False, "hospital_name": None, "hospital_distance_m": None,
            "dust_suppression_required": False, "dust_suppression_observed": False,
            "last_inspection_date": "2026-04-30", "violation_count_90d": 0,
        },
        {
            "slug": "taramani-ascendas-infra-site",
            "name": "Ascendas IT Park Phase-3 Infrastructure Expansion Works",
            "type": "construction",
            "description": "Commercial IT park extension, excavation, concrete batching, and material hauling.",
            "d_lon": 0.014, "d_lat": -0.010,
            "permit_id": "GCC/CONST/2026/0884",
            "compliance_status": "compliant",
            "compliance_note": "Continuous street sweeper and water sprinkling verified",
            "near_school": True, "school_name": "Bala Vidya Mandir Senior Secondary School", "school_distance_m": 530,
            "near_hospital": True, "hospital_name": "Apollo Speciality Hospital OMR", "hospital_distance_m": 620,
            "dust_suppression_required": True, "dust_suppression_observed": True,
            "last_inspection_date": "2026-05-22", "violation_count_90d": 0,
        },
    ],
}
